# 当代码推动到 dev 分支时，执行当前工作流程
# 更多配置信息: https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy serverless

on: #监听的事件和分支配置
  push:
    branches:
      - master
      - development

jobs:
  deploy:
    name: deploy serverless
    runs-on: ubuntu-latest
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: build
        run: GOOS=linux GOARCH=amd64 go build -o release/server/main cmd/server/main.go
      - name: install serverless
        run: npm install -g serverless
      - name: copy bootstrap
        run: cp deployments/scf_bootstrap release/server/scf_bootstrap
      - name: deploy serverless
        run: sls deploy
        env: # 环境变量
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} #您的腾讯云账号 sercret ID
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} #您的腾讯云账号 sercret key
          use_env: true
          run_addr: 0.0.0.0:9000
          bestdori_api: ${{ secrets.BESTDORI_API }}
          mysql: ${{ secrets.MYSQL }}
          meilisearch: ${{ secrets.MEILISEARCH }}
          meilisearch_key: ${{ secrets.MEILISEARCH_KEY }}
          scf_apigw_serviceID: ${{ secrets.SCF_APIGW_SERVICEID }}
          GLOBAL_ACCELERATOR_NA : true