basePath: /v2
definitions:
  Controllers.ChartDisplayOutput:
    properties:
      chart_set:
        items:
          $ref: '#/definitions/chartFormat.Chart'
        type: array
      result:
        type: boolean
    type: object
  Controllers.ChartDisplayOutputID:
    properties:
      chart_set:
        $ref: '#/definitions/chartFormat.Chart'
      result:
        type: boolean
    type: object
  Controllers.InfoOutput:
    properties:
      list: {}
      result:
        type: boolean
    type: object
  Controllers.MapInfoOutput:
    properties:
      mapDifficultyExtend:
        description: MapDifficultyExtend
      mapDifficultyStandard:
        $ref: '#/definitions/Models.MapDifficultyStandard'
      mapInfoExtend:
        description: MapInfoExtend
      mapInfoStandard:
        $ref: '#/definitions/Models.MapInfoStandard'
      result:
        type: boolean
    type: object
  Models.APIVersion:
    properties:
      version:
        type: string
    type: object
  Models.Distribution:
    properties:
      hit:
        items:
          type: number
        type: array
      note:
        items:
          type: number
        type: array
    type: object
  Models.MapDifficultyStandard:
    properties:
      blueWhiteDifficulty:
        type: number
      difficulty:
        type: number
      maxScreenNPS:
        type: number
      totalHPS:
        type: number
      totalNPS:
        type: number
    type: object
  Models.MapInfoStandard:
    properties:
      bpmhigh:
        type: number
      bpmlow:
        type: number
      distribution:
        $ref: '#/definitions/Models.Distribution'
      irregular:
        description: 存在多压/交叉（出张）0 失败 1 标准 2 非标准
        type: integer
      irregularInfo:
        description: 无法分析的第一个错误情况
        type: string
      mainBPM:
        type: number
      maxScreenNPS:
        type: number
      noteCount:
        $ref: '#/definitions/Models.NoteCount'
      totalHPS:
        type: number
      totalHitNote:
        type: integer
      totalNPS:
        type: number
      totalNote:
        type: integer
      totalTime:
        type: number
    type: object
  Models.NoteCount:
    properties:
      direction:
        properties:
          left:
            type: integer
          right:
            type: integer
          total:
            type: integer
        type: object
      flick:
        type: integer
      single:
        type: integer
      slideEnd:
        type: integer
      slideHidden:
        type: integer
      slideStart:
        type: integer
      slideTick:
        type: integer
      sprhythm:
        type: boolean
    type: object
  chartFormat.Chart:
    properties:
      artists:
        description: 谱面的艺术家
        type: string
      author:
        properties:
          authorID:
            description: 谱面作者用户名
            type: integer
          authorName:
            description: Author_Other 其他作者时使用的名义
            type: string
        type: object
      chartID:
        description: 已提交：BanGround社区谱面ID,未提交：Bestdori社区Ex/SpID
        type: integer
      diffs:
        properties:
          bestdoriChartID:
            description: Bestdori的谱面ID 0 就是未发表
            type: integer
          bpmhigh:
            type: number
          bpmlow:
            type: number
          diff:
            type: integer
          irregular:
            description: 存在多压/交叉（出张）0 失败 1 标准 2 非标准
            type: integer
          irregularInfo:
            description: 无法分析的第一个错误情况
            type: string
          level:
            type: integer
          mainBPM:
            type: number
          totalNPS:
            type: number
          totalNote:
            type: integer
          totalTime:
            type: number
        type: object
      rel:
        description: 访问网址
        type: string
      songUrl:
        description: 谱面资源
        properties:
          audio:
            type: string
          cover:
            type: string
        type: object
      submitted:
        description: 是否已经提交到BanGround社区
        type: boolean
      title:
        description: 谱面的标题
        type: string
    type: object
  utils.MapInput:
    properties:
      Options:
        additionalProperties:
          type: string
        type: object
      map: {}
      map_format_in:
        type: string
    type: object
  utils.MapOutput:
    properties:
      map: {}
      result:
        type: boolean
    type: object
host: 127.0.0.1:8080
info:
  contact:
    name: 6QHTSK
  description: api 计算Bestdori谱面难度，获得Bestdori数据，常见Bandori谱面格式转换等
  license:
    name: Apache 2.0
    url: https://mit-license.org/
  title: ayachan API
  version: "2.0"
paths:
  /chart-display:
    get:
      description: 获取谱面展示数据库的谱面
      parameters:
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 对应的谱面
          schema:
            $ref: '#/definitions/Controllers.ChartDisplayOutput'
      summary: 获取谱面展示数据库的谱面
      tags:
      - chartDisplay
  /chart-display/:chartID:
    get:
      description: 获取谱面展示数据库的指定ID的谱面
      parameters:
      - description: 谱面ID
        in: path
        name: chartID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 对应的谱面
          schema:
            $ref: '#/definitions/Controllers.ChartDisplayOutputID'
      summary: 获取谱面展示数据库的谱面
      tags:
      - chartDisplay
  /charter-like-rank:
    get:
      description: 获取谱师获赞数的排行
      parameters:
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 对应的谱面
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱师获赞数的排行
      tags:
      - BestdoriInfo
  /charter-list:
    get:
      description: 获取所追踪的谱师列表
      produces:
      - application/json
      responses:
        "200":
          description: 谱师列表
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取所追踪的谱师列表
      tags:
      - BestdoriInfo
  /charter-post-rank:
    get:
      description: 获取谱师发表谱面的排行
      parameters:
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 对应的谱面
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱师发表谱面的排行
      tags:
      - BestdoriInfo
  /charter/:charter/basic-info:
    get:
      description: 获取谱师的基本信息
      parameters:
      - description: 谱师用户名
        in: path
        name: charter
        required: true
        type: string
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 谱师基础信息
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱师的基本信息
      tags:
      - BestdoriInfo
  /charter/:charter/like-rank:
    get:
      description: 获取谱师发表的赞数排行
      parameters:
      - description: 谱师用户名
        in: path
        name: charter
        required: true
        type: string
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 谱面列表
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱师发表的赞数排行
      tags:
      - BestdoriInfo
  /charter/:charter/note-rank:
    get:
      description: 获取谱师发表的音符数排行
      parameters:
      - description: 谱师用户名
        in: path
        name: charter
        required: true
        type: string
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 谱面列表
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱师发表的音符数排行
      tags:
      - BestdoriInfo
  /charter/:charter/nps-rank:
    get:
      description: 获取谱师发表的谱面的NPS排行
      parameters:
      - description: 谱师用户名
        in: path
        name: charter
        required: true
        type: string
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 谱面列表
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱师发表的谱面的NPS排行
      tags:
      - BestdoriInfo
  /charter/:charter/post:
    get:
      description: 获取谱师发表的谱面
      parameters:
      - description: 谱师用户名
        in: path
        name: charter
        required: true
        type: string
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 谱面列表
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱师发表的谱面
      tags:
      - BestdoriInfo
  /charter/:charter/time-rank:
    get:
      description: 获取谱师发表的谱面的时间排行
      parameters:
      - description: 谱师用户名
        in: path
        name: charter
        required: true
        type: string
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 谱面列表
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱师发表的谱面的时间排行
      tags:
      - BestdoriInfo
  /map-data:
    post:
      consumes:
      - application/json
      description: 根据用户上传的谱面获取指定格式谱面
      parameters:
      - description: 需转换的谱面
        in: body
        name: map
        required: true
        schema:
          $ref: '#/definitions/utils.MapInput'
      produces:
      - application/json
      responses:
        "200":
          description: 对应的谱面
          schema:
            $ref: '#/definitions/utils.MapOutput'
      summary: 从用户上传谱面获取谱面
      tags:
      - mapData
  /map-data/bestdori/:chartID:
    get:
      description: 根据谱面ID、谱面难度从Bestdori获取谱面
      parameters:
      - description: 谱面ID
        in: path
        name: chartID
        required: true
        type: integer
      - description: 谱面难度差分指定，默认Expert
        in: query
        name: diff
        type: string
      - description: 输出谱面格式，默认BestdoriV2
        in: query
        name: map_format_out
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 对应的谱面
          schema:
            $ref: '#/definitions/utils.MapOutput'
      summary: 从Bestdori获取谱面
      tags:
      - mapData
  /map-info:
    post:
      consumes:
      - application/json
      description: 根据用户上传的谱面获取指定格式谱面信息
      parameters:
      - description: 需转换的谱面
        in: body
        name: map
        required: true
        schema:
          $ref: '#/definitions/utils.MapInput'
      produces:
      - application/json
      responses:
        "200":
          description: 对应的谱面
          schema:
            $ref: '#/definitions/Controllers.MapInfoOutput'
      summary: 从用户上传谱面获取谱面信息
      tags:
      - mapInfo
  /map-info/bestdori/:chartID:
    get:
      description: 根据谱面ID、谱面难度从Bestdori获取谱面并分析得到数据
      parameters:
      - description: 谱面ID
        in: path
        name: chartID
        required: true
        type: integer
      - description: 谱面难度差分指定，默认Expert
        in: query
        name: diff
        type: string
      - description: 输出谱面格式，默认BestdoriV2
        in: query
        name: map_format_out
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 解析的谱面信息
          schema:
            $ref: '#/definitions/Controllers.MapInfoOutput'
      summary: 从Bestdori获取谱面并分析数据
      tags:
      - mapInfo
  /song-like-rank:
    get:
      description: 获取谱面获赞数的排行
      parameters:
      - description: 页码,默认1
        in: query
        name: page
        type: integer
      - description: 页面限制，默认20
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 对应的谱面
          schema:
            $ref: '#/definitions/Controllers.InfoOutput'
      summary: 获取谱面获赞数的排行
      tags:
      - BestdoriInfo
  /version:
    get:
      description: 根据内部信息得到API的版本
      produces:
      - application/json
      responses:
        "200":
          description: 获得的API版本号
          schema:
            $ref: '#/definitions/Models.APIVersion'
      summary: 获得API版本
      tags:
      - Version
swagger: "2.0"
